name: CI

on:

  push:

    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt-get install -y build-essential python-dev-is-python3 python3-numpy

    - name: Build library
      run: make PYTHON=python && cp -r permanent/ docs/

    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "make html"
        docs-folder: "docs/"

    - uses: actions/upload-pages-artifact@v3
      with:
        name: github-pages
        path: docs/build/html/

  deploy:

    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-latest

    needs: build

    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    steps:
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
